### ISSUE TITLE
Estudo e Pesquisa sobre Modelo de contrato de software.

### ISSUE THREAD

**Issue by GabrielVictorino8266** [GabrielVictorino8266/pi_2_semestre#21]
Objetivo final
- Levantar um modelo de contrato de software para o projeto.

**Comment by orlandosaraivajr** [comment]
Se o projeto for de escopo aberto, no meu repositório tem um modelo que pode ser utilizado por vocês. Segue o link: 

https://github.com/orlandosaraivajr/estudos/blob/master/modelo-dekode-contrato-desenvolvimento.doc

**Comment by GabrielVictorino8266** [comment]
![{3FDB14EE-07E0-4F5C-A521-C87FCF645568}](https://github.com/user-attachments/assets/3eba1d5d-fb1d-43e4-ae0b-24d40a8ea2b1)
