### ISSUE TITLE
Diário de Bordo Rafael e Slides de Apresentação (Parte Responsável)

### ISSUE THREAD

**Issue by GabrielVictorino8266** [GabrielVictorino8266/pi_2_semestre#41]
Ao finalizar, responder aqui as suas atividades finalizadas.

**Comment by rafabotezelli** [comment]
Boa noite, segue em anexo, o diario de bordo e a apresentação 
[Web Project Proposal by Slidesgo.pptx](https://github.com/user-attachments/files/17972963/Web.Project.Proposal.by.Slidesgo.pptx)
[DIARIODEBORDO.txt](https://github.com/user-attachments/files/17972967/DIARIODEBORDO.txt)
