### ISSUE TITLE
DOCS - Criação de Diagrama de Classes

### ISSUE THREAD

**Issue by GabrielVictorino8266** [GabrielVictorino8266/pi_2_semestre#9]
Criar diagrama de classe para o sistema.

Responsável: João

**Comment by GabrielVictorino8266** [comment]
Finalizado.

**Comment by JOAOVITOR2024** [comment]
Finalizado e encaminhado para o Gabriel no teams

**Comment by GabrielVictorino8266** [comment]
![{3FDB14EE-07E0-4F5C-A521-C87FCF645568}](https://github.com/user-attachments/assets/68914eac-cee1-41c1-a292-4a21c2d0e023)
